name: mobile
description: GymBro — app afiliado (Flutter)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  provider: ^6.1.5
  mobile_scanner: ^6.0.11
  path_provider: ^2.1.5
  # Clon local en la raíz del monorepo (ver docs/15-kuatia-deuda-rename.md)
  identity_core_dart:
    path: ../identity_core_dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
