-- Prisma enum extend (Postgres 16: ADD VALUE in migration tx is OK).
ALTER TYPE "NotificationEventCode" ADD VALUE IF NOT EXISTS 'RESERVATION_CONFIRMED';
ALTER TYPE "NotificationEventCode" ADD VALUE IF NOT EXISTS 'RESERVATION_CANCELLED';
ALTER TYPE "NotificationEventCode" ADD VALUE IF NOT EXISTS 'WAITLIST_PROMOTED';
ALTER TYPE "NotificationEventCode" ADD VALUE IF NOT EXISTS 'REFUND_EXECUTED';
ALTER TYPE "NotificationEventCode" ADD VALUE IF NOT EXISTS 'CONTRACT_EXPIRING';
ALTER TYPE "NotificationEventCode" ADD VALUE IF NOT EXISTS 'CONTRACT_IN_TOLERANCE';
