ALTER TYPE "NotificationEventCode" ADD VALUE IF NOT EXISTS 'PLATFORM_PLAN_PAID';
ALTER TYPE "NotificationEventCode" ADD VALUE IF NOT EXISTS 'PLATFORM_PLAN_EXPIRING';
ALTER TYPE "NotificationEventCode" ADD VALUE IF NOT EXISTS 'PLATFORM_PLAN_EXPIRING_DEBIT';
ALTER TYPE "NotificationEventCode" ADD VALUE IF NOT EXISTS 'PLATFORM_PLAN_IN_TOLERANCE';
ALTER TYPE "NotificationEventCode" ADD VALUE IF NOT EXISTS 'PLATFORM_DEBIT_CHARGE_FAILED';
ALTER TYPE "NotificationEventCode" ADD VALUE IF NOT EXISTS 'PLATFORM_DEBIT_MANDATE_FAILED';
